# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks

# Annotate should not run in any envs other than development. It is for annotating source
# files based on migrations
if Rails.env.development?
  Annotate.load_tasks
end
